# Generated by Django 4.2.11 on 2025-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenementss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('jour', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('infos_complementaires', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Calendrier',
        ),
    ]
