# Generated by Django 4.2.11 on 2025-08-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_evenementss_delete_calendrier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evenementss',
            new_name='Evenements',
        ),
    ]
