# Generated by Django 4.2.11 on 2025-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_rename_evenementss_evenements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenements',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='evenements',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='evenements',
            name='infos_complementaires',
        ),
        migrations.RemoveField(
            model_name='evenements',
            name='jour',
        ),
        migrations.AddField(
            model_name='evenements',
            name='organisateur_nom',
            field=models.CharField(default='inconnu', max_length=150),
        ),
    ]
