# Generated by Django 5.2.5 on 2025-09-13 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapp", "0004_remove_evenements_heure_debut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenements",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="evenements",
            name="lieu",
            field=models.CharField(default="En ligne", max_length=150),
        ),
        migrations.AlterField(
            model_name="evenements",
            name="organisateur_nom",
            field=models.CharField(default="Inconnu", max_length=150),
        ),
    ]
