# Generated by Django 5.2.5 on 2025-09-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monapp", "0005_evenements_date_evenements_lieu_and_more"),
    ]

    operations = []
